# Note: there are many handy hints in comments in this example -- remove them
# when you've finalized your recipe

# Jinja variables help maintain the recipe as you'll update the version only
# here.
# Using the name variable with the URL in line 14 is convenient
# when copying and pasting from another recipe, but not really needed.
# {% set name = "loos" %}
# {% set version = "3.2beta" %}
# {% set version = "3.2" %}

package:
  name: "loos"
  version: "3.2"

source:
  # url: https://github.com/GrossfieldLab/loos/archive/{{ name }}-{{ version }}.tar.gz
  url: https://github.com/GrossfieldLab/loos/archive/loos-3.2.tgz
  sha256: bba2d554dcc9eda812f00050ebe2e287b675135dbf073f8649988d339d31603f

build:
  number: 0
  # Only python 3.x
  skip: True  # [py<35, win]
  # skip: True  # [py<35]
  # we don't do Windows
  # skip: True  # [win]

requirements:
  build:
    - {{ compiler('cxx') }}
  host:
    - python
    - scons
    - swig
    - numpy
    - scipy
    - boost
    - openblas
    - libnetcdf
    - lapack
    - eigen
    - openssl
  run:
    - python
    - numpy
    - scipy
test:
  imports:
    - loos

about:
  home: https://github.com/GrossfieldLab/loos
  license: GPLv3
  license_family: GPL
  license_file: COPYING
  summary: 'LOOS is a suite for analyzing molecular dynamics simulations'
  doc_url: https://github.com/GrossfieldLab/loos
  dev_url: https://github.com/GrossfieldLab/loos

extra:
  recipe-maintainers:
    - agrossfield
