{% set version = "3.2" %}

package:
  name: "loos"
  version: "{{ version }}"

source:
  url: https://raw.githubusercontent.com/GrossfieldLab/loos/master/archive/loos-{{ version }}.tar.gz
  sha256: 4d3806e712e4ae2190385db15773a1af2319dc1c7774e0d44f51370a9061bfbc

build:
  number: 0
  # Only python 3.x, no windows
  skip: True  # [win or py<35]

requirements:
  build:
    - {{ compiler('cxx') }}
    - {{ compiler('fortran') }}
    - scons
    - numpy
    - boost
    - openblas
    - libnetcdf
    - lapack
    - eigen
    - swig
  host:
    - python
    - scons
    - numpy
    - scipy
    - boost
    - openblas
    - libnetcdf
    - lapack
    - eigen
    - openssl
  run:
    - python
    - {{ pin_compatible('numpy') }}
    - {{ pin_compatible('scipy') }}
test:
  imports:
    - loos

about:
  home: https://github.com/GrossfieldLab/loos
  license: GPL-3.0-only
  license_family: GPL
  license_file: COPYING
  summary: 'LOOS is a suite for analyzing molecular dynamics simulations'
  doc_url: https://github.com/GrossfieldLab/loos
  dev_url: https://github.com/GrossfieldLab/loos
  description: |
    LOOS is a library for rapidly developing new tools to analyze molecular
    dynamics simulations. It is distributed with ~100 tools. The core library is
    written in C++, with a python interface provided via swig.

extra:
  recipe-maintainers:
    - agrossfield
